name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        paths:
          ["api", "db"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        # https://github.com/actions/checkout

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v2
        # https://github.com/docker/setup-buildx-action

      - name: Cache Docker layers
        uses: actions/cache@v3
        # https://github.com/actions/cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: ${{ runner.os }}-buildx-

      - name: Login to container registry
        uses: docker/login-action@v2
        # https://github.com/docker/login-action
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set variable for image tag
        id: set-var
        run: |
          SHA=$(git rev-parse --short ${{ github.sha }})
          echo "::set-output name=tag::$SHA"

      - name: Build and Push
        uses: docker/build-push-action@v3
        # https://github.com/docker/build-push-action
        with:
          context: .
          file: ./build/${{ matrix.paths }}/Dockerfile
          push: true
          tags: ghcr.io/${{ github.actor }}/go-rest-api-docker_${{ matrix.paths }}:${{ steps.set-var.outputs.tag }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      # Until this issue close
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
